In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.simplefilter('ignore')

In [2]:
import describe as db

In [3]:
df = pd.read_csv('books.csv')
df.head()

bookID                                              title  \
0       1  Harry Potter and the Half-Blood Prince (Harry ...   
1       2  Harry Potter and the Order of the Phoenix (Har...   
2       4  Harry Potter and the Chamber of Secrets (Harry...   
3       5  Harry Potter and the Prisoner of Azkaban (Harr...   
4       8  Harry Potter Boxed Set  Books 1-5 (Harry Potte...   

                      authors average_rating        isbn         isbn13  \
0  J.K. Rowling/Mary GrandPré           4.57   439785960  9780439785969   
1  J.K. Rowling/Mary GrandPré           4.49   439358078  9780439358071   
2                J.K. Rowling           4.42   439554896  9780439554893   
3  J.K. Rowling/Mary GrandPré           4.56  043965548X  9780439655484   
4  J.K. Rowling/Mary GrandPré           4.78   439682584  9780439682589   

  language_code   num_pages  ratings_count  text_reviews_count  \
0           eng         652        2095690               27591   
1           eng         870        2153167               29221   
2           eng         352           6333                 244   
3           eng         435        2339585               36325   
4           eng        2690          41428                 164   

  publication_date        publisher Unnamed: 12  
0        9/16/2006  Scholastic Inc.         NaN  
1         9/1/2004  Scholastic Inc.         NaN  
2        11/1/2003       Scholastic         NaN  
3         5/1/2004  Scholastic Inc.         NaN  
4        9/13/2004       Scholastic         NaN

# DU

In [4]:
db.describe(df)

variable   dtype  count  unique  missing value
0               bookID   int64  11127   11127              0
1                title  object  11127   10352              0
2              authors  object  11127    6643              0
3       average_rating  object  11127     213              0
4                 isbn  object  11127   11126              0
5               isbn13  object  11127   11127              0
6        language_code  object  11127      31              0
7            num_pages  object  11127     999              0
8        ratings_count   int64  11127    5294              0
9   text_reviews_count   int64  11127    1822              0
10    publication_date  object  11127    3682              0
11           publisher  object  11127    2294              0
12         Unnamed: 12  object  11127       5          11123

In [5]:
df.columns.tolist()

['bookID',
 'title',
 'authors',
 'average_rating',
 'isbn',
 'isbn13',
 'language_code',
 '  num_pages',
 'ratings_count',
 'text_reviews_count',
 'publication_date',
 'publisher',
 'Unnamed: 12']

In [6]:
df.rename(columns={'  num_pages':'num_pages'},inplace=True)

In [7]:
df.shape

(11127, 13)

In [8]:
df['Unnamed: 12'].unique()

array([nan, 'Harvard University Press', 'Cold Spring Press',
       'Huntington House Publishers', 'Brown Son & Ferguson Ltd.'],
      dtype=object)

In [9]:
df['Unnamed: 12'].dropna()

3348       Harvard University Press
4702              Cold Spring Press
5877    Huntington House Publishers
8979      Brown Son & Ferguson Ltd.
Name: Unnamed: 12, dtype: object

In [10]:
df.loc[[3348,4702,5877,8979 ]]

bookID                                              title  \
3348   12224  Streetcar Suburbs: The Process of Growth in Bo...   
4702   16914                  The Tolkien Fan's Medieval Reader   
5877   22128                     Patriots (The Coming Collapse)   
8979   34889  Brown's Star Atlas: Showing All The Bright Sta...   

                                       authors  \
3348                           Sam Bass Warner   
4702  David E. Smith (Turgon of TheOneRing.net   
5877                              James Wesley   
8979                                     Brown   

                                         average_rating  isbn      isbn13  \
3348                                  Jr./Sam B. Warner  3.58   674842111   
4702   one of the founding members of this Tolkien w...  3.58  1593600119   
5877                                             Rawles  3.63  156384155X   
8979                                     Son & Ferguson     0   851742718   

     language_code num_pages  ratings_count  text_reviews_count  \
3348   9.78067E+12     en-US            236                  61   
4702   9.78159E+12       eng            400                  26   
5877   9.78156E+12       eng            342                  38   
8979   9.78085E+12       eng             49                   0   

     publication_date  publisher                  Unnamed: 12  
3348                6  4/20/2004     Harvard University Press  
4702                4   4/6/2004            Cold Spring Press  
5877                4  1/15/1999  Huntington House Publishers  
8979                0   5/1/1977    Brown Son & Ferguson Ltd.

In [11]:
df['language_code'].unique()

array(['eng', 'en-US', 'fre', 'spa', 'en-GB', 'mul', 'grc', 'enm',
       'en-CA', 'ger', 'jpn', 'ara', 'nl', 'zho', 'lat', 'por', 'srp',
       '9.78067E+12', 'ita', '9.78159E+12', 'rus', '9.78156E+12', 'msa',
       'glg', 'wel', 'swe', 'nor', '9.78085E+12', 'tur', 'gla', 'ale'],
      dtype=object)

In [12]:
df['language_code'].value_counts()

eng            8908
en-US          1408
spa             218
en-GB           214
fre             144
ger              99
jpn              46
mul              19
zho              14
grc              11
por              10
en-CA             7
ita               5
lat               3
enm               3
rus               2
swe               2
ara               1
wel               1
gla               1
tur               1
9.78085E+12       1
nor               1
9.78156E+12       1
glg               1
msa               1
nl                1
9.78159E+12       1
9.78067E+12       1
srp               1
ale               1
Name: language_code, dtype: int64

In [13]:
df.duplicated().sum()

0

# DP

In [14]:
df.loc[3348, ['authors','average_rating', 'isbn13', 'language_code', 
              'num_pages','ratings_count','text_reviews_count' ,'publication_date', 'publisher']] = ['Sam Bass Warner',
    3.58,  '674842111', 'eng', 236, 61, 6, '4/20/2004', 'Harvard University Press']

In [15]:
df.loc[4702, ['authors','average_rating', 'isbn13', 'language_code', 
              'num_pages','ratings_count','text_reviews_count' ,'publication_date', 'publisher']] = ['David E. Smith',
    3.58,  '9781593600112', 'eng', 400, 26, 4, '4/6/2004', 'Cold Spring Press']

In [16]:
df.loc[5877, ['authors','average_rating', 'isbn13', 'language_code', 
              'num_pages','ratings_count','text_reviews_count' ,'publication_date', 'publisher']] = ['James Wesley Rawles',
    3.63, '9.78156E+12', 'eng', 342, 38, 4, '1/15/1999', 'Huntington House Publishers']

In [17]:
df.loc[8979, ['authors','average_rating', 'isbn13', 'language_code', 
              'num_pages','ratings_count','text_reviews_count' ,'publication_date', 'publisher']] = ['Brown,Son & Ferguson',
    0, '9.78085E+12', 'eng', 49, 0, 0, '5/1/1977', 'Brown Son & Ferguson Ltd']

In [18]:
df['average_rating']=df['average_rating'].astype(float)

In [19]:
df.loc[[3348,4702,5877,8979 ]]

bookID                                              title  \
3348   12224  Streetcar Suburbs: The Process of Growth in Bo...   
4702   16914                  The Tolkien Fan's Medieval Reader   
5877   22128                     Patriots (The Coming Collapse)   
8979   34889  Brown's Star Atlas: Showing All The Bright Sta...   

                   authors  average_rating  isbn         isbn13 language_code  \
3348       Sam Bass Warner            3.58  3.58      674842111           eng   
4702        David E. Smith            3.58  3.58  9781593600112           eng   
5877   James Wesley Rawles            3.63  3.63    9.78156E+12           eng   
8979  Brown,Son & Ferguson            0.00     0    9.78085E+12           eng   

     num_pages  ratings_count  text_reviews_count publication_date  \
3348       236             61                   6        4/20/2004   
4702       400             26                   4         4/6/2004   
5877       342             38                   4        1/15/1999   
8979        49              0                   0         5/1/1977   

                        publisher                  Unnamed: 12  
3348     Harvard University Press     Harvard University Press  
4702            Cold Spring Press            Cold Spring Press  
5877  Huntington House Publishers  Huntington House Publishers  
8979     Brown Son & Ferguson Ltd    Brown Son & Ferguson Ltd.

In [20]:
df.drop(columns=['Unnamed: 12'],inplace=True)

In [21]:
df['num_pages']=df['num_pages'].astype(int)

In [22]:
df['authors'] = df['authors'].str.replace('/', ', ')

In [23]:
df['publisher'] = df['publisher'].str.replace('.', '', regex=False)

In [24]:
df['publication_year'] = pd.to_datetime(df['publication_date'], errors='coerce').dt.year

In [25]:
df['publication_year'] = pd.to_numeric(df['publication_year'], errors='coerce').astype('Int64')

In [26]:
df['average_rating_cat']=pd.cut(df['average_rating'],bins=[-1,1,2,3,4,5],
                       labels=['worst','bad','average','good','excellent'])

In [27]:
df['ratings_count_cat']=pd.cut(df['ratings_count'],bins=[-1,1000000,2000000,3000000,4000000,5000000],
                       labels=['very low','low','normal','high','very high'])

In [28]:
df['page_category'] = pd.cut(df['num_pages'], bins=[-1, 100, 500, 1000, 7000],
                             labels=['Short', 'Medium', 'Long', 'Very Long'])

In [29]:
df["author_publisher_year"] = (
    df["authors"] + " , " +
    df["publisher"] + ", " +
    df['publication_year'].astype(str) + ", " +
    df['ratings_count_cat'].astype(str) + ", " +
    df['page_category'].astype(str) + ", " +
    df['average_rating_cat'].astype(str) + ", " +
    df['language_code']
)

In [30]:
df['author_publisher_year']

0        J.K. Rowling, Mary GrandPré , Scholastic Inc, ...
1        J.K. Rowling, Mary GrandPré , Scholastic Inc, ...
2        J.K. Rowling , Scholastic, 2003, very low, Med...
3        J.K. Rowling, Mary GrandPré , Scholastic Inc, ...
4        J.K. Rowling, Mary GrandPré , Scholastic, 2004...
                               ...                        
11122    William T. Vollmann, Larry McCaffery, Michael ...
11123    William T. Vollmann , Penguin Books, 1988, ver...
11124    William T. Vollmann , Penguin Books, 1993, ver...
11125    William T. Vollmann , Ecco, 2007, very low, Me...
11126    Mark Twain , Edimat Libros, 2006, very low, Me...
Name: author_publisher_year, Length: 11127, dtype: object

In [31]:
df=df.drop(columns=['publication_year','average_rating_cat','ratings_count_cat','page_category'])

In [32]:
db.describe(df)

variable    dtype  count  unique  missing value
0                  bookID    int64  11127   11127              0
1                   title   object  11127   10352              0
2                 authors   object  11127    6643              0
3          average_rating  float64  11127     209              0
4                    isbn   object  11127   11126              0
5                  isbn13   object  11127   11127              0
6           language_code   object  11127      27              0
7               num_pages    int32  11127     997              0
8           ratings_count    int64  11127    5294              0
9      text_reviews_count    int64  11127    1822              0
10       publication_date   object  11127    3679              0
11              publisher   object  11127    2285              0
12  author_publisher_year   object  11127   10679              0

In [33]:
df.head()

bookID                                              title  \
0       1  Harry Potter and the Half-Blood Prince (Harry ...   
1       2  Harry Potter and the Order of the Phoenix (Har...   
2       4  Harry Potter and the Chamber of Secrets (Harry...   
3       5  Harry Potter and the Prisoner of Azkaban (Harr...   
4       8  Harry Potter Boxed Set  Books 1-5 (Harry Potte...   

                       authors  average_rating        isbn         isbn13  \
0  J.K. Rowling, Mary GrandPré            4.57   439785960  9780439785969   
1  J.K. Rowling, Mary GrandPré            4.49   439358078  9780439358071   
2                 J.K. Rowling            4.42   439554896  9780439554893   
3  J.K. Rowling, Mary GrandPré            4.56  043965548X  9780439655484   
4  J.K. Rowling, Mary GrandPré            4.78   439682584  9780439682589   

  language_code  num_pages  ratings_count  text_reviews_count  \
0           eng        652        2095690               27591   
1           eng        870        2153167               29221   
2           eng        352           6333                 244   
3           eng        435        2339585               36325   
4           eng       2690          41428                 164   

  publication_date       publisher  \
0        9/16/2006  Scholastic Inc   
1         9/1/2004  Scholastic Inc   
2        11/1/2003      Scholastic   
3         5/1/2004  Scholastic Inc   
4        9/13/2004      Scholastic   

                               author_publisher_year  
0  J.K. Rowling, Mary GrandPré , Scholastic Inc, ...  
1  J.K. Rowling, Mary GrandPré , Scholastic Inc, ...  
2  J.K. Rowling , Scholastic, 2003, very low, Med...  
3  J.K. Rowling, Mary GrandPré , Scholastic Inc, ...  
4  J.K. Rowling, Mary GrandPré , Scholastic, 2004...

# M

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()
feature_vectors = vec.fit_transform(df['author_publisher_year'])
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 131346 stored elements and shape (11127, 10075)>
  Coords	Values
  (0, 2790)	0.07143810327318503
  (0, 2908)	0.10840480874039247
  (0, 5538)	0.16677571837593466
  (0, 6747)	0.46298119079028144
  (0, 76)	0.1682687403959053
  (0, 4405)	0.31639424956443946
  (0, 8114)	0.31815264399702226
  (0, 3613)	0.48940523893299187
  (0, 5922)	0.31860063245439346
  (0, 7853)	0.4126919258329741
  (1, 74)	0.19425700422758352
  (1, 2790)	0.07109092956188454
  (1, 2908)	0.10787798484601636
  (1, 5538)	0.16596522450151074
  (1, 6747)	0.46073120246606286
  (1, 4405)	0.31485664202976893
  (1, 8114)	0.3166064910462066
  (1, 3613)	0.48702683545718106
  (1, 5922)	0.31705230237669113
  (1, 7853)	0.41068633244582486
  (2, 6156)	0.1286814176526766
  (2, 5588)	0.10002212457528205
  (2, 9374)	0.1001840456975211
  (2, 73)	0.34772179080034277
  (2, 2790)	0.12210163529797179
  :	:
  (11124, 3560)	0.13270819134561962
  (11124, 1083)	0.2171342069796251
  (1112

In [35]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.96696345 0.49291595 ... 0.00737638 0.00694643 0.03028397]
 [0.96696345 1.         0.49052048 ... 0.00734054 0.00691268 0.        ]
 [0.49291595 0.49052048 1.         ... 0.04355872 0.0410198  0.02290327]
 ...
 [0.00737638 0.00734054 0.04355872 ... 1.         0.61196137 0.03240042]
 [0.00694643 0.00691268 0.0410198  ... 0.61196137 1.         0.03051189]
 [0.03028397 0.         0.02290327 ... 0.03240042 0.03051189 1.        ]]


In [36]:
print(similarity.shape)

(11127, 11127)


In [37]:
list_of_books = df['title'].tolist()
print(list_of_books)

['Harry Potter and the Half-Blood Prince (Harry Potter  #6)', 'Harry Potter and the Order of the Phoenix (Harry Potter  #5)', 'Harry Potter and the Chamber of Secrets (Harry Potter  #2)', 'Harry Potter and the Prisoner of Azkaban (Harry Potter  #3)', 'Harry Potter Boxed Set  Books 1-5 (Harry Potter  #1-5)', 'Unauthorized Harry Potter Book Seven News: "Half-Blood Prince" Analysis and Speculation', 'Harry Potter Collection (Harry Potter  #1-6)', "The Ultimate Hitchhiker's Guide: Five Complete Novels and One Story (Hitchhiker's Guide to the Galaxy  #1-5)", "The Ultimate Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy  #1-5)", "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy  #1)", "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy  #1)", "The Ultimate Hitchhiker's Guide (Hitchhiker's Guide to the Galaxy  #1-5)", 'A Short History of Nearly Everything', "Bill Bryson's African Diary", "Bryson's Dictionary of Troublesome Words: A 

In [38]:
book_name = input('Enter any book name: ')

Enter any book name: Harry Potter and the Half-Blood Prince (Harry Potter  #6)


In [39]:
import difflib
close_match = difflib.get_close_matches(book_name,list_of_books)
print(close_match)

['Harry Potter and the Half-Blood Prince (Harry Potter  #6)', 'Harry Potter and the Half-Blood Prince (Harry Potter  #6)', "Harry Potter and the Philosopher's Stone (Harry Potter  #1)"]


In [40]:
close_one = close_match[0]
print(close_one)

Harry Potter and the Half-Blood Prince (Harry Potter  #6)


In [41]:
index_of_book = df[df.title == close_one]['bookID'].index[0]
print(index_of_book)

0


In [42]:
similarity_score = list(enumerate(similarity[index_of_book]))
print(similarity_score)

[(0, 1.0000000000000002), (1, 0.9669634492667417), (2, 0.4929159484757266), (3, 0.9497568557519156), (4, 0.7786166700115696), (5, 0.0), (6, 0.5213321329567024), (7, 0.05989305616615425), (8, 0.05824090276383452), (9, 0.02354303123886186), (10, 0.017185890620105337), (11, 0.05691759945927549), (12, 0.06077594804467708), (13, 0.006851871987066598), (14, 0.0071132895450749765), (15, 0.023150622172690354), (16, 0.006995105316366627), (17, 0.0062057748048701105), (18, 0.006264132971520911), (19, 0.006355250128489794), (20, 0.0062492675401454), (21, 0.0636032108062375), (22, 0.057139554741870414), (23, 0.2602162059030337), (24, 0.041375731926869476), (25, 0.01588076936368012), (26, 0.01774265923380741), (27, 0.01782594912904989), (28, 0.004529718010074833), (29, 0.003321383105623252), (30, 0.006354936538047683), (31, 0.013857343382463482), (32, 0.0), (33, 0.002325250220071738), (34, 0.03532512339402244), (35, 0.021605574520019304), (36, 0.01627331025699326), (37, 0.006204602815407892), (38, 

In [43]:
len(similarity_score)

11127

In [44]:
sorted_similar_books = sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_books)

[(0, 1.0000000000000002), (1, 0.9669634492667417), (3, 0.9497568557519156), (4416, 0.814561871893382), (4, 0.7786166700115696), (6, 0.5213321329567024), (2, 0.4929159484757266), (8876, 0.45512224240746024), (615, 0.3714933147977004), (307, 0.35114124997377594), (10679, 0.33992876576088327), (6391, 0.2879034063809137), (1697, 0.2831551597725188), (9471, 0.2730430058162969), (2116, 0.2713780461189233), (6397, 0.26952720647062056), (1956, 0.2657306505314975), (9167, 0.2657306505314975), (23, 0.2602162059030337), (11070, 0.25968306335612606), (988, 0.2540058043180712), (613, 0.2501119647815564), (6749, 0.24891547163676486), (5533, 0.2444567890862114), (1462, 0.2405911153588836), (1233, 0.23658499978223144), (9166, 0.2355999422280305), (6249, 0.23284438915776867), (10350, 0.23208838189737988), (10347, 0.23105414802406554), (4413, 0.22198195179953867), (947, 0.21398737434289108), (8560, 0.21299179948178812), (946, 0.20900738824291493), (7220, 0.2011733643435992), (10495, 0.19925081256302268)

In [45]:
li =[]
for i in sorted_similar_books:
    li.append(i[0])
    if len(li)==10:
        break

In [46]:
li

[0, 1, 3, 4416, 4, 6, 2, 8876, 615, 307]

In [47]:
df1=pd.DataFrame({})
for z in li:
     df1[z]=(df.loc[z][['bookID','title','isbn','language_code']])

In [48]:
df1.T.set_index('bookID')


title        isbn  \
bookID                                                                  
1       Harry Potter and the Half-Blood Prince (Harry ...   439785960   
2       Harry Potter and the Order of the Phoenix (Har...   439358078   
5       Harry Potter and the Prisoner of Azkaban (Harr...  043965548X   
15881   Harry Potter and the Chamber of Secrets (Harry...   439064864   
8       Harry Potter Boxed Set  Books 1-5 (Harry Potte...   439682584   
10           Harry Potter Collection (Harry Potter  #1-6)   439827604   
4       Harry Potter and the Chamber of Secrets (Harry...   439554896   
34318   Harry Potter and the Sorcerer's Stone (Harry P...   786222727   
2005    Harry Potter and the Half-Blood Prince (Harry ...   747584664   
960                  Angels & Demons (Robert Langdon  #1)  1416524797   

       language_code  
bookID                
1                eng  
2                eng  
5                eng  
15881            eng  
8                eng  
10               eng  
4                eng  
34318            eng  
2005             eng  
960              eng